name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nox-under-test
        run: |
          python -m pip install nox
      - name: Install redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - name: Run tests on ${{ matrix.os }}
        run: |
          nox --non-interactive --session "tests-${{ matrix.python-version}}" -- -m "not ci_disabled" --full-trace 
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Nox-under-test
        run: |
          python -m pip install nox
      - name: Lint
        run: nox --non-interactive --session "lint"
      - name: Run mypy
        run: nox --non-interactive --session "mypy"
